CREATE TRIGGER NoteModifiedAt
    ON [dbo].[Notes]
    FOR INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

	IF ((SELECT TRIGGER_NESTLEVEL()) > 1) RETURN;

	DECLARE @Id INT

	SELECT @Id = INSERTED.Id
	FROM INSERTED

	UPDATE dbo.Notes
	SET ModifiedAt = GETDATE()
	WHERE Id = @Id
END
